### ISSUE TITLE
WSubmission

### ISSUE THREAD

**Issue by bl82** [bl82/web-ui-developer-puzzle#8]
### Submission

Ready to submit? Please review the checklist below.

- [ ] Have you opened four pull-requests for the tasks? Make sure they are opened with the correct target branch.
- [ ] Task 1: `chore/code-review -> master`   #4 #3 
- [ ] Task 2: `feat/instant-search -> chore/code-review` #5 
- [ ] Task 3: `feat/undo-actions -> chore/code-review` #6 
- [ ] Task 4: `feat/mark-as-read -> chore/code-review` #7 
- [ ] Are all your features working as per requirements?
- [ ] Are lint, test, e2e passing?
- [ ] Once you are done, send the link to your repo to your T-Mobile manager for evaluation.
